server:
  port: 8080

spring:
  application:
    name: leadbridge-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: tenant-service
          uri: lb://leadbridge-tenant-service
          predicates:
            - Path=/api/tenants/**
        - id: lead-service
          uri: lb://leadbridge-lead-service
          predicates:
            - Path=/api/leads/**
        - id: email-service
          uri: lb://leadbridge-email-service
          predicates:
            - Path=/api/emails/**
        - id: report-service
          uri: lb://leadbridge-report-service
          predicates:
            - Path=/api/reports/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/leadbridge}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
