server:
  port: 8081

spring:
  application:
    name: leadbridge-tenant-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5439}/${DB_NAME:leadbridge}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/leadbridge}
  flyway:
    enabled: true
    validate-on-migrate: false
    baseline-on-migrate: true
    out-of-order: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8180}
  realm: master
  client-id: admin-cli
  username: admin
  password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

management:
  endpoints:
    web:
      exposure:
        include: health
